services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: todo
    ports:
      - "5432:5432"
    volumes:
      - todo_pg_data:/var/lib/postgresql/data


  backend:
    build:
      context: /home/joni/IdeaProjects/TodoToUseReact
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/todo
      SPRING_DATASOURCE_USERNAME: todo
      SPRING_DATASOURCE_PASSWORD: todo
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_FLYWAY_ENABLED: "true"
    ports:
      - "8080:8080"
  
  frontend:
    build:
      context: /home/joni/Documents/repos/front-todo-reac-spring
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  todo_pg_data:
